server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-progresso:5432/progresso}
    username: ${SPRING_DATASOURCE_USERNAME:progresso}
    password: ${SPRING_DATASOURCE_PASSWORD:progresso}
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

flyway:
  enabled: true
  locations: classpath:db/migration

logging:
  level:
    root: INFO
