name: gateway-api
services:
  gateway:
    build:
      context: .
    container_name: gateway
    env_file: .env
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - elearning-net

networks:
  elearning-net:
    external: true
